[project]
name = "assignment01"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12,<3.13"
dependencies = [
    "jupyter>=1.1.1",
    "nltk>=3.9.1",
    "tqdm>=4.67.1",
]
